schema {
  query: Query
  mutation: Mutation
}

type Query {
  bodyStatsById(id: Int!): BodyStats @cost(weight: "10")
  bodyStats(
    where: BodyStatsFilterInput @cost(weight: "10")
    order: [BodyStatsSortInput!] @cost(weight: "10")
  ): [BodyStats!]! @cost(weight: "10")
  helloPerson(name: String! = "World"): String!
}

type Mutation {
  addBodyStats(bodyStats: BodyStatsDtoInput!): BodyStats! @cost(weight: "10")
  updateBodyStats(id: Int!, bodyStats: BodyStatsDtoInput!): BodyStats @cost(weight: "10")
  deleteBodyStats(id: Int!): Boolean! @cost(weight: "10")
}

type BodyStats {
  id: Int!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
  date: DateTime!
  weight: Float!
  bodyFatPercentage: Float!
  musclePercentage: Float!
  waterPercentage: Float!
  boneMass: Float!
  comments(
    order: [CommentSortInput!] @cost(weight: "10")
    where: CommentFilterInput @cost(weight: "10")
  ): [Comment!]!
}

type Comment {
  id: Int!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
  content: String!
}

input BodyStatsDtoInput {
  date: DateTime!
  weight: Float!
  bodyFatPercentage: Float!
  musclePercentage: Float!
  waterPercentage: Float!
  boneMass: Float!
  comments: [CommentInput!]!
}

input BodyStatsFilterInput {
  and: [BodyStatsFilterInput!]
  or: [BodyStatsFilterInput!]
  id: IntOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
  date: DateTimeOperationFilterInput
  weight: FloatOperationFilterInput
  bodyFatPercentage: FloatOperationFilterInput
  musclePercentage: FloatOperationFilterInput
  waterPercentage: FloatOperationFilterInput
  boneMass: FloatOperationFilterInput
  comments: ListFilterInputTypeOfCommentFilterInput
}

input BodyStatsSortInput {
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
  date: SortEnumType @cost(weight: "10")
  weight: SortEnumType @cost(weight: "10")
  bodyFatPercentage: SortEnumType @cost(weight: "10")
  musclePercentage: SortEnumType @cost(weight: "10")
  waterPercentage: SortEnumType @cost(weight: "10")
  boneMass: SortEnumType @cost(weight: "10")
}

input CommentFilterInput {
  and: [CommentFilterInput!]
  or: [CommentFilterInput!]
  id: IntOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
  content: StringOperationFilterInput
}

input CommentInput {
  id: Int!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
  content: String!
}

input CommentSortInput {
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
  content: SortEnumType @cost(weight: "10")
}

input DateTimeOperationFilterInput {
  eq: DateTime @cost(weight: "10")
  neq: DateTime @cost(weight: "10")
  in: [DateTime] @cost(weight: "10")
  nin: [DateTime] @cost(weight: "10")
  gt: DateTime @cost(weight: "10")
  ngt: DateTime @cost(weight: "10")
  gte: DateTime @cost(weight: "10")
  ngte: DateTime @cost(weight: "10")
  lt: DateTime @cost(weight: "10")
  nlt: DateTime @cost(weight: "10")
  lte: DateTime @cost(weight: "10")
  nlte: DateTime @cost(weight: "10")
}

input FloatOperationFilterInput {
  eq: Float @cost(weight: "10")
  neq: Float @cost(weight: "10")
  in: [Float] @cost(weight: "10")
  nin: [Float] @cost(weight: "10")
  gt: Float @cost(weight: "10")
  ngt: Float @cost(weight: "10")
  gte: Float @cost(weight: "10")
  ngte: Float @cost(weight: "10")
  lt: Float @cost(weight: "10")
  nlt: Float @cost(weight: "10")
  lte: Float @cost(weight: "10")
  nlte: Float @cost(weight: "10")
}

input IntOperationFilterInput {
  eq: Int @cost(weight: "10")
  neq: Int @cost(weight: "10")
  in: [Int] @cost(weight: "10")
  nin: [Int] @cost(weight: "10")
  gt: Int @cost(weight: "10")
  ngt: Int @cost(weight: "10")
  gte: Int @cost(weight: "10")
  ngte: Int @cost(weight: "10")
  lt: Int @cost(weight: "10")
  nlt: Int @cost(weight: "10")
  lte: Int @cost(weight: "10")
  nlte: Int @cost(weight: "10")
}

input ListFilterInputTypeOfCommentFilterInput {
  all: CommentFilterInput @cost(weight: "10")
  none: CommentFilterInput @cost(weight: "10")
  some: CommentFilterInput @cost(weight: "10")
  any: Boolean @cost(weight: "10")
}

input StringOperationFilterInput {
  and: [StringOperationFilterInput!]
  or: [StringOperationFilterInput!]
  eq: String @cost(weight: "10")
  neq: String @cost(weight: "10")
  contains: String @cost(weight: "20")
  ncontains: String @cost(weight: "20")
  in: [String] @cost(weight: "10")
  nin: [String] @cost(weight: "10")
  startsWith: String @cost(weight: "20")
  nstartsWith: String @cost(weight: "20")
  endsWith: String @cost(weight: "20")
  nendsWith: String @cost(weight: "20")
}

input UuidOperationFilterInput {
  eq: UUID @cost(weight: "10")
  neq: UUID @cost(weight: "10")
  in: [UUID] @cost(weight: "10")
  nin: [UUID] @cost(weight: "10")
  gt: UUID @cost(weight: "10")
  ngt: UUID @cost(weight: "10")
  gte: UUID @cost(weight: "10")
  ngte: UUID @cost(weight: "10")
  lt: UUID @cost(weight: "10")
  nlt: UUID @cost(weight: "10")
  lte: UUID @cost(weight: "10")
  nlte: UUID @cost(weight: "10")
}

enum SortEnumType {
  ASC
  DESC
}

"The `DateTime` scalar type represents a date and time with time zone offset information."
scalar DateTime @specifiedBy(url: "https://scalars.graphql.org/chillicream/date-time.html")

"The `UUID` scalar type represents a Universally Unique Identifier (UUID) as defined by RFC 9562."
scalar UUID @specifiedBy(url: "https://scalars.graphql.org/chillicream/uuid.html")

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on SCALAR | OBJECT | FIELD_DEFINITION | ARGUMENT_DEFINITION | ENUM | INPUT_FIELD_DEFINITION
