schema {
  query: Query
  mutation: Mutation
}

type Query {
  "Fetches an object given its ID."
  node("ID of the object." id: ID!): Node @cost(weight: "10")
  "Lookup nodes by a list of IDs."
  nodes("The list of node IDs." ids: [ID!]!): [Node]! @cost(weight: "10")
  activityMerges(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: ActivityMergeFilterInput @cost(weight: "10")
    order: [ActivityMergeSortInput!] @cost(weight: "10")
  ): ActivityMergeConnection!
    @listSize(
      assumedSize: 200
      slicingArguments: ["first", "last"]
      slicingArgumentDefaultValue: 100
      sizedFields: ["edges", "nodes"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
  activities(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: ActivityFilterInput @cost(weight: "10")
    order: [ActivitySortInput!] @cost(weight: "10")
  ): ActivityConnection!
    @listSize(
      assumedSize: 200
      slicingArguments: ["first", "last"]
      slicingArgumentDefaultValue: 100
      sizedFields: ["edges", "nodes"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
  bodyStatsById(id: ID!): BodyStats @cost(weight: "10")
  bodyStats(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: BodyStatsFilterInput @cost(weight: "10")
    order: [BodyStatsSortInput!] @cost(weight: "10")
  ): BodyStatsConnection!
    @listSize(
      assumedSize: 200
      slicingArguments: ["first", "last"]
      slicingArgumentDefaultValue: 100
      sizedFields: ["edges", "nodes"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
  events(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: EventFilterInput @cost(weight: "10")
    order: [EventSortInput!] @cost(weight: "10")
  ): EventConnection!
    @listSize(
      assumedSize: 200
      slicingArguments: ["first", "last"]
      slicingArgumentDefaultValue: 100
      sizedFields: ["edges", "nodes"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
  gadgets(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: GadgetFilterInput @cost(weight: "10")
    order: [GadgetSortInput!] @cost(weight: "10")
  ): GadgetConnection!
    @listSize(
      assumedSize: 200
      slicingArguments: ["first", "last"]
      slicingArgumentDefaultValue: 100
      sizedFields: ["edges", "nodes"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
  tags(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: TagFilterInput @cost(weight: "10")
    order: [TagSortInput!] @cost(weight: "10")
  ): TagConnection!
    @listSize(
      assumedSize: 200
      slicingArguments: ["first", "last"]
      slicingArgumentDefaultValue: 100
      sizedFields: ["edges", "nodes"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
  me: User! @cost(weight: "10")
  vehicles(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
    where: VehicleFilterInput @cost(weight: "10")
    order: [VehicleSortInput!] @cost(weight: "10")
  ): VehicleConnection!
    @listSize(
      assumedSize: 200
      slicingArguments: ["first", "last"]
      slicingArgumentDefaultValue: 100
      sizedFields: ["edges", "nodes"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
  helloPerson(name: String! = "World"): String!
}

type Mutation {
  createActivityMerge(name: String, activityIds: [ID!]!): ActivityMerge!
    @cost(weight: "10")
  renameActivityMerge(id: ID!, name: String): ActivityMerge @cost(weight: "10")
  addActivityToMerge(mergeId: ID!, activityId: ID!): ActivityMerge
    @cost(weight: "10")
  removeActivityFromMerge(mergeId: ID!, activityId: ID!): ActivityMerge
    @cost(weight: "10")
  deleteActivityMerge(id: ID!): ID @cost(weight: "10")
  createActivity(activity: ActivityInput!): Activity! @cost(weight: "10")
  updateActivity(id: ID!, activity: ActivityInput!): Activity
    @cost(weight: "10")
  deleteActivity(id: ID!): ID @cost(weight: "10")
  addBodyStats(bodyStats: BodyStatsInput!): BodyStats! @cost(weight: "10")
  updateBodyStats(id: ID!, bodyStats: BodyStatsInput!): BodyStats
    @cost(weight: "10")
  deleteBodyStats(id: ID!): ID @cost(weight: "10")
  createEvent(event: EventInput!): Event! @cost(weight: "10")
  updateEvent(id: ID!, event: EventInput!): Event @cost(weight: "10")
  deleteEvent(id: ID!): ID @cost(weight: "10")
  createGadget(gadget: GadgetInput!): Gadget! @cost(weight: "10")
  updateGadget(id: ID!, gadget: GadgetInput!): Gadget @cost(weight: "10")
  deleteGadget(id: ID!): ID @cost(weight: "10")
  createTag(tag: TagInput!): Tag! @cost(weight: "10")
  updateTag(id: ID!, tag: TagInput!): Tag @cost(weight: "10")
  deleteTag(id: ID!): ID @cost(weight: "10")
  createMaintenanceCycle(maintenanceCycle: MaintenanceCycleInput!): MaintenanceCycle!
    @cost(weight: "10")
  updateMaintenanceCycle(id: ID!, maintenanceCycle: MaintenanceCycleInput!): MaintenanceCycle
    @cost(weight: "10")
  deleteMaintenanceCycle(id: ID!): ID @cost(weight: "10")
  createVehicle(vehicle: VehicleInput!): Vehicle! @cost(weight: "10")
  updateVehicle(id: ID!, vehicle: VehicleInput!): Vehicle @cost(weight: "10")
  deleteVehicle(id: ID!): ID @cost(weight: "10")
}

type Activity implements Node {
  id: ID!
  date: DateTime!
  type: ActivityType!
  time: Int!
  distance: Float!
  averageSpeed: Float
  elevationGain: Float
  tss: Float
  description: String
  heartRateMin: Int
  heartRateMax: Int
  heartRateAverage: Int
  mood: Mood
  effort: Int
  wind: Wind
  source: Source!
  stravaActivityId: Long
  vehicle: Vehicle
  merge: ActivityMerge
  tags: [Tag!]!
  gadgets: [Gadget!]!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

"A connection to a list of items."
type ActivityConnection {
  "A list of edges."
  edges: [ActivityEdge!]
  "A flattened list of the nodes"
  nodes: [Activity!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int! @cost(weight: "10")
}

type ActivityEdge {
  "The item at the end of the edge."
  node: Activity!
  "A cursor for use in pagination."
  cursor: String!
}

type ActivityMerge implements Node {
  id: ID!
  name: String
  activities: [Activity!]!
  totalTime: Int!
  totalDistance: Float!
  totalElevationGain: Float
  totalTss: Float
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

"A connection to a list of items."
type ActivityMergeConnection {
  "A list of edges."
  edges: [ActivityMergeEdge!]
  "A flattened list of the nodes"
  nodes: [ActivityMerge!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int! @cost(weight: "10")
}

type ActivityMergeEdge {
  "The item at the end of the edge."
  node: ActivityMerge!
  "A cursor for use in pagination."
  cursor: String!
}

type BodyStats implements Node {
  id: ID!
  date: DateTime!
  weight: Float!
  bodyFatPercentage: Float!
  musclePercentage: Float!
  waterPercentage: Float!
  boneMass: Float!
  comment: String
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

"A connection to a list of items."
type BodyStatsConnection {
  "A list of edges."
  edges: [BodyStatsEdge!]
  "A flattened list of the nodes"
  nodes: [BodyStats!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int! @cost(weight: "10")
}

type BodyStatsEdge {
  "The item at the end of the edge."
  node: BodyStats!
  "A cursor for use in pagination."
  cursor: String!
}

type Event implements Node {
  id: ID!
  name: String!
  type: EventType!
  description: String
  startDate: LocalDate!
  endDate: LocalDate
  tags: [Tag!]!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

"A connection to a list of items."
type EventConnection {
  "A list of edges."
  edges: [EventEdge!]
  "A flattened list of the nodes"
  nodes: [Event!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int! @cost(weight: "10")
}

type EventEdge {
  "The item at the end of the edge."
  node: Event!
  "A cursor for use in pagination."
  cursor: String!
}

type Gadget implements Node {
  id: ID!
  tags: [Tag!]!
  vehicles: [Vehicle!]!
  maintenanceCycles: [MaintenanceCycle!]!
  brand: String!
  model: String!
  nickname: String
  purchaseDate: LocalDate
  description: String
  deactivationDate: LocalDate
  price: Decimal
  source: Source!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

"A connection to a list of items."
type GadgetConnection {
  "A list of edges."
  edges: [GadgetEdge!]
  "A flattened list of the nodes"
  nodes: [Gadget!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int! @cost(weight: "10")
}

type GadgetEdge {
  "The item at the end of the edge."
  node: Gadget!
  "A cursor for use in pagination."
  cursor: String!
}

type MaintenanceCycle implements Node {
  id: ID!
  vehicle: Vehicle
  gadget: Gadget
  name: String!
  intervalDistance: Float
  intervalDays: Int
  lastServiceDate: LocalDate
  description: String
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

"A cursor that points to a specific page."
type PageCursor {
  "The page number."
  page: Int!
  "The cursor."
  cursor: String!
}

"Information about pagination in a connection."
type PageInfo {
  "Indicates whether more edges exist following the set defined by the clients arguments."
  hasNextPage: Boolean!
  "Indicates whether more edges exist prior the set defined by the clients arguments."
  hasPreviousPage: Boolean!
  "When paginating backwards, the cursor to continue."
  startCursor: String
  "When paginating forwards, the cursor to continue."
  endCursor: String
  "A list of cursors to continue paginating forwards."
  forwardCursors: [PageCursor!]!
  "A list of cursors to continue paginating backwards."
  backwardCursors: [PageCursor!]!
}

type Tag implements Node {
  id: ID!
  name: String!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

"A connection to a list of items."
type TagConnection {
  "A list of edges."
  edges: [TagEdge!]
  "A flattened list of the nodes"
  nodes: [Tag!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int! @cost(weight: "10")
}

type TagEdge {
  "The item at the end of the edge."
  node: Tag!
  "A cursor for use in pagination."
  cursor: String!
}

type User implements Node {
  id: ID!
  email: String!
  firstName: String!
  lastName: String!
  language: Language!
  role: Role!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

type Vehicle implements Node {
  id: ID!
  stravaGearId: String
  tags: [Tag!]!
  gadgets: [Gadget!]!
  maintenanceCycles: [MaintenanceCycle!]!
  brand: String!
  model: String!
  nickname: String
  purchaseDate: LocalDate
  description: String
  deactivationDate: LocalDate
  price: Decimal
  source: Source!
  uid: UUID!
  createdAt: DateTime!
  modifiedAt: DateTime!
}

"A connection to a list of items."
type VehicleConnection {
  "A list of edges."
  edges: [VehicleEdge!]
  "A flattened list of the nodes"
  nodes: [Vehicle!]
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "Identifies the total count of items in the connection."
  totalCount: Int! @cost(weight: "10")
}

type VehicleEdge {
  "The item at the end of the edge."
  node: Vehicle!
  "A cursor for use in pagination."
  cursor: String!
}

"The node interface is implemented by entities that have a global unique identifier."
interface Node {
  id: ID!
}

input ActivityFilterInput {
  and: [ActivityFilterInput!]
  or: [ActivityFilterInput!]
  date: DateTimeOperationFilterInput
  type: ActivityTypeOperationFilterInput
  time: IntOperationFilterInput
  distance: FloatOperationFilterInput
  averageSpeed: FloatOperationFilterInput
  elevationGain: FloatOperationFilterInput
  tss: FloatOperationFilterInput
  description: StringOperationFilterInput
  heartRateMin: IntOperationFilterInput
  heartRateMax: IntOperationFilterInput
  heartRateAverage: IntOperationFilterInput
  mood: NullableOfMoodOperationFilterInput
  effort: IntOperationFilterInput
  wind: NullableOfWindOperationFilterInput
  source: SourceOperationFilterInput
  stravaActivityId: LongOperationFilterInput
  vehicle: VehicleFilterInput
  merge: ActivityMergeFilterInput
  tags: ListFilterInputTypeOfTagFilterInput
  gadgets: ListFilterInputTypeOfGadgetFilterInput
  id: IdOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
}

input ActivityInput {
  date: DateTime!
  type: ActivityType!
  time: Int!
  distance: Float!
  elevationGain: Float
  description: String
  heartRateMin: Int
  heartRateMax: Int
  heartRateAverage: Int
  mood: Mood
  effort: Int
  wind: Wind
  vehicleId: ID
  gadgetIds: [ID!]!
  tagIds: [ID!]!
}

input ActivityMergeFilterInput {
  and: [ActivityMergeFilterInput!]
  or: [ActivityMergeFilterInput!]
  name: StringOperationFilterInput
  activities: ListFilterInputTypeOfActivityFilterInput
  totalTime: IntOperationFilterInput
  totalDistance: FloatOperationFilterInput
  totalElevationGain: FloatOperationFilterInput
  totalTss: FloatOperationFilterInput
  id: IdOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
}

input ActivityMergeSortInput {
  name: SortEnumType @cost(weight: "10")
  totalTime: SortEnumType @cost(weight: "10")
  totalDistance: SortEnumType @cost(weight: "10")
  totalElevationGain: SortEnumType @cost(weight: "10")
  totalTss: SortEnumType @cost(weight: "10")
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
}

input ActivitySortInput {
  date: SortEnumType @cost(weight: "10")
  type: SortEnumType @cost(weight: "10")
  time: SortEnumType @cost(weight: "10")
  distance: SortEnumType @cost(weight: "10")
  averageSpeed: SortEnumType @cost(weight: "10")
  elevationGain: SortEnumType @cost(weight: "10")
  tss: SortEnumType @cost(weight: "10")
  description: SortEnumType @cost(weight: "10")
  heartRateMin: SortEnumType @cost(weight: "10")
  heartRateMax: SortEnumType @cost(weight: "10")
  heartRateAverage: SortEnumType @cost(weight: "10")
  mood: SortEnumType @cost(weight: "10")
  effort: SortEnumType @cost(weight: "10")
  wind: SortEnumType @cost(weight: "10")
  source: SortEnumType @cost(weight: "10")
  stravaActivityId: SortEnumType @cost(weight: "10")
  vehicle: VehicleSortInput @cost(weight: "10")
  merge: ActivityMergeSortInput @cost(weight: "10")
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
}

input ActivityTypeOperationFilterInput {
  eq: ActivityType @cost(weight: "10")
  neq: ActivityType @cost(weight: "10")
  in: [ActivityType!] @cost(weight: "10")
  nin: [ActivityType!] @cost(weight: "10")
}

input BodyStatsFilterInput {
  and: [BodyStatsFilterInput!]
  or: [BodyStatsFilterInput!]
  date: DateTimeOperationFilterInput
  weight: FloatOperationFilterInput
  bodyFatPercentage: FloatOperationFilterInput
  musclePercentage: FloatOperationFilterInput
  waterPercentage: FloatOperationFilterInput
  boneMass: FloatOperationFilterInput
  comment: StringOperationFilterInput
  id: IdOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
}

input BodyStatsInput {
  date: DateTime!
  weight: Float!
  bodyFatPercentage: Float!
  musclePercentage: Float!
  waterPercentage: Float!
  boneMass: Float!
  comment: String
}

input BodyStatsSortInput {
  date: SortEnumType @cost(weight: "10")
  weight: SortEnumType @cost(weight: "10")
  bodyFatPercentage: SortEnumType @cost(weight: "10")
  musclePercentage: SortEnumType @cost(weight: "10")
  waterPercentage: SortEnumType @cost(weight: "10")
  boneMass: SortEnumType @cost(weight: "10")
  comment: SortEnumType @cost(weight: "10")
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
}

input DateTimeOperationFilterInput {
  eq: DateTime @cost(weight: "10")
  neq: DateTime @cost(weight: "10")
  in: [DateTime] @cost(weight: "10")
  nin: [DateTime] @cost(weight: "10")
  gt: DateTime @cost(weight: "10")
  ngt: DateTime @cost(weight: "10")
  gte: DateTime @cost(weight: "10")
  ngte: DateTime @cost(weight: "10")
  lt: DateTime @cost(weight: "10")
  nlt: DateTime @cost(weight: "10")
  lte: DateTime @cost(weight: "10")
  nlte: DateTime @cost(weight: "10")
}

input DecimalOperationFilterInput {
  eq: Decimal @cost(weight: "10")
  neq: Decimal @cost(weight: "10")
  in: [Decimal] @cost(weight: "10")
  nin: [Decimal] @cost(weight: "10")
  gt: Decimal @cost(weight: "10")
  ngt: Decimal @cost(weight: "10")
  gte: Decimal @cost(weight: "10")
  ngte: Decimal @cost(weight: "10")
  lt: Decimal @cost(weight: "10")
  nlt: Decimal @cost(weight: "10")
  lte: Decimal @cost(weight: "10")
  nlte: Decimal @cost(weight: "10")
}

input EventFilterInput {
  and: [EventFilterInput!]
  or: [EventFilterInput!]
  name: StringOperationFilterInput
  type: EventTypeOperationFilterInput
  description: StringOperationFilterInput
  startDate: LocalDateOperationFilterInput
  endDate: LocalDateOperationFilterInput
  tags: ListFilterInputTypeOfTagFilterInput
  id: IdOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
}

input EventInput {
  name: String!
  type: EventType!
  description: String
  startDate: LocalDate!
  endDate: LocalDate
  tagIds: [ID!]!
}

input EventSortInput {
  name: SortEnumType @cost(weight: "10")
  type: SortEnumType @cost(weight: "10")
  description: SortEnumType @cost(weight: "10")
  startDate: SortEnumType @cost(weight: "10")
  endDate: SortEnumType @cost(weight: "10")
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
}

input EventTypeOperationFilterInput {
  eq: EventType @cost(weight: "10")
  neq: EventType @cost(weight: "10")
  in: [EventType!] @cost(weight: "10")
  nin: [EventType!] @cost(weight: "10")
}

input FloatOperationFilterInput {
  eq: Float @cost(weight: "10")
  neq: Float @cost(weight: "10")
  in: [Float] @cost(weight: "10")
  nin: [Float] @cost(weight: "10")
  gt: Float @cost(weight: "10")
  ngt: Float @cost(weight: "10")
  gte: Float @cost(weight: "10")
  ngte: Float @cost(weight: "10")
  lt: Float @cost(weight: "10")
  nlt: Float @cost(weight: "10")
  lte: Float @cost(weight: "10")
  nlte: Float @cost(weight: "10")
}

input GadgetFilterInput {
  and: [GadgetFilterInput!]
  or: [GadgetFilterInput!]
  tags: ListFilterInputTypeOfTagFilterInput
  vehicles: ListFilterInputTypeOfVehicleFilterInput
  maintenanceCycles: ListFilterInputTypeOfMaintenanceCycleFilterInput
  brand: StringOperationFilterInput
  model: StringOperationFilterInput
  nickname: StringOperationFilterInput
  purchaseDate: LocalDateOperationFilterInput
  description: StringOperationFilterInput
  deactivationDate: LocalDateOperationFilterInput
  price: DecimalOperationFilterInput
  source: SourceOperationFilterInput
  id: IdOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
}

input GadgetInput {
  vehicleIds: [ID!]!
  brand: String!
  model: String!
  nickname: String
  purchaseDate: LocalDate
  description: String
  deactivationDate: LocalDate
  price: Decimal
  tagIds: [ID!]!
}

input GadgetSortInput {
  brand: SortEnumType @cost(weight: "10")
  model: SortEnumType @cost(weight: "10")
  nickname: SortEnumType @cost(weight: "10")
  purchaseDate: SortEnumType @cost(weight: "10")
  description: SortEnumType @cost(weight: "10")
  deactivationDate: SortEnumType @cost(weight: "10")
  price: SortEnumType @cost(weight: "10")
  source: SortEnumType @cost(weight: "10")
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
}

input IdOperationFilterInput {
  eq: ID @cost(weight: "10")
  neq: ID @cost(weight: "10")
  in: [ID] @cost(weight: "10")
  nin: [ID] @cost(weight: "10")
}

input IntOperationFilterInput {
  eq: Int @cost(weight: "10")
  neq: Int @cost(weight: "10")
  in: [Int] @cost(weight: "10")
  nin: [Int] @cost(weight: "10")
  gt: Int @cost(weight: "10")
  ngt: Int @cost(weight: "10")
  gte: Int @cost(weight: "10")
  ngte: Int @cost(weight: "10")
  lt: Int @cost(weight: "10")
  nlt: Int @cost(weight: "10")
  lte: Int @cost(weight: "10")
  nlte: Int @cost(weight: "10")
}

input ListFilterInputTypeOfActivityFilterInput {
  all: ActivityFilterInput @cost(weight: "10")
  none: ActivityFilterInput @cost(weight: "10")
  some: ActivityFilterInput @cost(weight: "10")
  any: Boolean @cost(weight: "10")
}

input ListFilterInputTypeOfEventFilterInput {
  all: EventFilterInput @cost(weight: "10")
  none: EventFilterInput @cost(weight: "10")
  some: EventFilterInput @cost(weight: "10")
  any: Boolean @cost(weight: "10")
}

input ListFilterInputTypeOfGadgetFilterInput {
  all: GadgetFilterInput @cost(weight: "10")
  none: GadgetFilterInput @cost(weight: "10")
  some: GadgetFilterInput @cost(weight: "10")
  any: Boolean @cost(weight: "10")
}

input ListFilterInputTypeOfMaintenanceCycleFilterInput {
  all: MaintenanceCycleFilterInput @cost(weight: "10")
  none: MaintenanceCycleFilterInput @cost(weight: "10")
  some: MaintenanceCycleFilterInput @cost(weight: "10")
  any: Boolean @cost(weight: "10")
}

input ListFilterInputTypeOfTagFilterInput {
  all: TagFilterInput @cost(weight: "10")
  none: TagFilterInput @cost(weight: "10")
  some: TagFilterInput @cost(weight: "10")
  any: Boolean @cost(weight: "10")
}

input ListFilterInputTypeOfVehicleFilterInput {
  all: VehicleFilterInput @cost(weight: "10")
  none: VehicleFilterInput @cost(weight: "10")
  some: VehicleFilterInput @cost(weight: "10")
  any: Boolean @cost(weight: "10")
}

input LocalDateOperationFilterInput {
  eq: LocalDate @cost(weight: "10")
  neq: LocalDate @cost(weight: "10")
  in: [LocalDate] @cost(weight: "10")
  nin: [LocalDate] @cost(weight: "10")
  gt: LocalDate @cost(weight: "10")
  ngt: LocalDate @cost(weight: "10")
  gte: LocalDate @cost(weight: "10")
  ngte: LocalDate @cost(weight: "10")
  lt: LocalDate @cost(weight: "10")
  nlt: LocalDate @cost(weight: "10")
  lte: LocalDate @cost(weight: "10")
  nlte: LocalDate @cost(weight: "10")
}

input LongOperationFilterInput {
  eq: Long @cost(weight: "10")
  neq: Long @cost(weight: "10")
  in: [Long] @cost(weight: "10")
  nin: [Long] @cost(weight: "10")
  gt: Long @cost(weight: "10")
  ngt: Long @cost(weight: "10")
  gte: Long @cost(weight: "10")
  ngte: Long @cost(weight: "10")
  lt: Long @cost(weight: "10")
  nlt: Long @cost(weight: "10")
  lte: Long @cost(weight: "10")
  nlte: Long @cost(weight: "10")
}

input MaintenanceCycleFilterInput {
  and: [MaintenanceCycleFilterInput!]
  or: [MaintenanceCycleFilterInput!]
  vehicle: VehicleFilterInput
  gadget: GadgetFilterInput
  name: StringOperationFilterInput
  intervalDistance: FloatOperationFilterInput
  intervalDays: IntOperationFilterInput
  lastServiceDate: LocalDateOperationFilterInput
  description: StringOperationFilterInput
  id: IdOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
}

input MaintenanceCycleInput {
  vehicleId: ID
  gadgetId: ID
  name: String!
  intervalDistance: Float
  intervalDays: Int
  lastServiceDate: LocalDate
  description: String
}

input NullableOfMoodOperationFilterInput {
  eq: Mood @cost(weight: "10")
  neq: Mood @cost(weight: "10")
  in: [Mood] @cost(weight: "10")
  nin: [Mood] @cost(weight: "10")
}

input NullableOfWindOperationFilterInput {
  eq: Wind @cost(weight: "10")
  neq: Wind @cost(weight: "10")
  in: [Wind] @cost(weight: "10")
  nin: [Wind] @cost(weight: "10")
}

input SourceOperationFilterInput {
  eq: Source @cost(weight: "10")
  neq: Source @cost(weight: "10")
  in: [Source!] @cost(weight: "10")
  nin: [Source!] @cost(weight: "10")
}

input StringOperationFilterInput {
  and: [StringOperationFilterInput!]
  or: [StringOperationFilterInput!]
  eq: String @cost(weight: "10")
  neq: String @cost(weight: "10")
  contains: String @cost(weight: "20")
  ncontains: String @cost(weight: "20")
  in: [String] @cost(weight: "10")
  nin: [String] @cost(weight: "10")
  startsWith: String @cost(weight: "20")
  nstartsWith: String @cost(weight: "20")
  endsWith: String @cost(weight: "20")
  nendsWith: String @cost(weight: "20")
}

input TagFilterInput {
  and: [TagFilterInput!]
  or: [TagFilterInput!]
  name: StringOperationFilterInput
  id: IdOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
}

input TagInput {
  name: String!
}

input TagSortInput {
  name: SortEnumType @cost(weight: "10")
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
}

input UuidOperationFilterInput {
  eq: UUID @cost(weight: "10")
  neq: UUID @cost(weight: "10")
  in: [UUID] @cost(weight: "10")
  nin: [UUID] @cost(weight: "10")
  gt: UUID @cost(weight: "10")
  ngt: UUID @cost(weight: "10")
  gte: UUID @cost(weight: "10")
  ngte: UUID @cost(weight: "10")
  lt: UUID @cost(weight: "10")
  nlt: UUID @cost(weight: "10")
  lte: UUID @cost(weight: "10")
  nlte: UUID @cost(weight: "10")
}

input VehicleFilterInput {
  and: [VehicleFilterInput!]
  or: [VehicleFilterInput!]
  stravaGearId: StringOperationFilterInput
  tags: ListFilterInputTypeOfTagFilterInput
  gadgets: ListFilterInputTypeOfGadgetFilterInput
  maintenanceCycles: ListFilterInputTypeOfMaintenanceCycleFilterInput
  brand: StringOperationFilterInput
  model: StringOperationFilterInput
  nickname: StringOperationFilterInput
  purchaseDate: LocalDateOperationFilterInput
  description: StringOperationFilterInput
  deactivationDate: LocalDateOperationFilterInput
  price: DecimalOperationFilterInput
  source: SourceOperationFilterInput
  id: IdOperationFilterInput
  uid: UuidOperationFilterInput
  createdAt: DateTimeOperationFilterInput
  modifiedAt: DateTimeOperationFilterInput
}

input VehicleInput {
  brand: String!
  model: String!
  nickname: String
  purchaseDate: LocalDate
  description: String
  deactivationDate: LocalDate
  price: Decimal
  tagIds: [ID!]!
}

input VehicleSortInput {
  stravaGearId: SortEnumType @cost(weight: "10")
  brand: SortEnumType @cost(weight: "10")
  model: SortEnumType @cost(weight: "10")
  nickname: SortEnumType @cost(weight: "10")
  purchaseDate: SortEnumType @cost(weight: "10")
  description: SortEnumType @cost(weight: "10")
  deactivationDate: SortEnumType @cost(weight: "10")
  price: SortEnumType @cost(weight: "10")
  source: SortEnumType @cost(weight: "10")
  id: SortEnumType @cost(weight: "10")
  uid: SortEnumType @cost(weight: "10")
  createdAt: SortEnumType @cost(weight: "10")
  modifiedAt: SortEnumType @cost(weight: "10")
}

enum ActivityType {
  ROAD
  MOUNTAIN
  GRAVEL
  INDOOR
}

enum EventType {
  CRASH
  INJURY
  ILLNESS
  REPAIR
  BREAK
  GOAL
  OTHER
}

enum Language {
  DE
  EN
}

enum Mood {
  VERY_BAD
  BAD
  NEUTRAL
  GOOD
  VERY_GOOD
}

enum Role {
  USER
  ADMINISTRATOR
}

enum SortEnumType {
  ASC
  DESC
}

enum Source {
  MANUAL
  STRAVA
}

enum Wind {
  CALM
  LIGHT
  MODERATE
  STRONG
  STORMY
}

"The `DateTime` scalar type represents a date and time with time zone offset information."
scalar DateTime
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/date-time.html")

"The `Decimal` scalar type represents a decimal floating-point number with high precision."
scalar Decimal
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/decimal.html")

"The `LocalDate` scalar type represents a date without time or time zone information."
scalar LocalDate
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/local-date.html")

"The `Long` scalar type represents a signed 64-bit integer."
scalar Long
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/long.html")

"The `UUID` scalar type represents a Universally Unique Identifier (UUID) as defined by RFC 9562."
scalar UUID
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/uuid.html")

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on
  | SCALAR
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | ENUM
  | INPUT_FIELD_DEFINITION

"The purpose of the `@listSize` directive is to either inform the static analysis about the size of returned lists (if that information is statically available), or to point the analysis to where to find that information."
directive @listSize(
  "The `assumedSize` argument can be used to statically define the maximum length of a list returned by a field."
  assumedSize: Int
  "The `slicingArguments` argument can be used to define which of the field's arguments with numeric type are slicing arguments, so that their value determines the size of the list returned by that field. It may specify a list of multiple slicing arguments."
  slicingArguments: [String!]
  "The `slicingArgumentDefaultValue` argument can be used to define a default value for a slicing argument, which is used if the argument is not present in a query."
  slicingArgumentDefaultValue: Int
  "The `sizedFields` argument can be used to define that the value of the `assumedSize` argument or of a slicing argument does not affect the size of a list returned by a field itself, but that of a list returned by one of its sub-fields."
  sizedFields: [String!]
  "The `requireOneSlicingArgument` argument can be used to inform the static analysis that it should expect that exactly one of the defined slicing arguments is present in a query. If that is not the case (i.e., if none or multiple slicing arguments are present), the static analysis may throw an error."
  requireOneSlicingArgument: Boolean = true
) on FIELD_DEFINITION